apiVersion: v1
kind: Service
metadata:
  name: consumer-metrics
  labels:
    app: consumer
spec:
  type: { { .Values.service.type } }
  ports:
    - name: http-metrics
      port: { { .Values.service.port } }
      targetPort: { { .Values.service.port } }
  selector:
    app: consumer