apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: producer-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: producer
  endpoints:
    - port: http-metrics
      interval: 1s